In [1]:
import numpy as np
import pandas as pd

In [2]:
df_train = pd.read_csv('data/train.csv')
df_train.head()

,id,journal_text,ambience_type,duration_min,sleep_hours,energy_level,stress_level,time_of_day,previous_day_mood,face_emotion_hint,reflection_quality,emotional_state,intensity
0,1,The ocean ambience helped me stop drifting and...,ocean,12,6.5,4,2,afternoon,mixed,calm_face,clear,focused,3
1,2,"I tried to relax during the forest ambience, y...",forest,35,6.0,2,4,evening,calm,tired_face,vague,restless,3
2,3,The forest session slowed my thoughts and I fe...,forest,3,NaN,2,1,night,overwhelmed,happy_face,clear,calm,3
3,4,"the mountain ambience was pleasant, though i c...",mountain,25,7.0,4,4,night,focused,calm_face,vague,neutral,1
4,5,"The rain session gave me a pause, but the pres...",rain,25,5.0,3,5,afternoon,NaN,tense_face,clear,overwhelmed,5


In [3]:
df_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   id                  1200 non-null   int64  
 1   journal_text        1200 non-null   str    
 2   ambience_type       1200 non-null   str    
 3   duration_min        1200 non-null   int64  
 4   sleep_hours         1193 non-null   float64
 5   energy_level        1200 non-null   int64  
 6   stress_level        1200 non-null   int64  
 7   time_of_day         1200 non-null   str    
 8   previous_day_mood   1185 non-null   str    
 9   face_emotion_hint   1077 non-null   str    
 10  reflection_quality  1200 non-null   str    
 11  emotional_state     1200 non-null   str    
 12  intensity           1200 non-null   int64  
dtypes: float64(1), int64(5), str(7)
memory usage: 122.0 KB


In [4]:
df_test = pd.read_csv('data/test.csv')
df_test.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   id                  120 non-null    int64  
 1   journal_text        120 non-null    str    
 2   ambience_type       120 non-null    str    
 3   duration_min        120 non-null    int64  
 4   sleep_hours         120 non-null    float64
 5   energy_level        120 non-null    int64  
 6   stress_level        120 non-null    int64  
 7   time_of_day         120 non-null    str    
 8   previous_day_mood   110 non-null    str    
 9   face_emotion_hint   101 non-null    str    
 10  reflection_quality  120 non-null    str    
dtypes: float64(1), int64(4), str(6)
memory usage: 10.4 KB


In [6]:
for column_name in df_train.columns:
    if column_name not in ['id', 'journal_text']:
        print(f"Unique values in column (Train) '{column_name}':")
        print(df_train[column_name].unique())
for column_name in df_test.columns:
    if column_name not in ['id', 'journal_text']:
        print(f"Unique values in column (Test) '{column_name}':")
        print(df_test[column_name].unique())

Unique values in column (Train) 'ambience_type':
<StringArray>
['ocean', 'forest', 'mountain', 'rain', 'cafe']
Length: 5, dtype: str
Unique values in column (Train) 'duration_min':
[12 35  3 25 20  8 15 18 10 30  5  7  4]
Unique values in column (Train) 'sleep_hours':
[6.5 6.  nan 7.  5.  8.  5.5 7.5 3.5 4.5 4.  8.5]
Unique values in column (Train) 'energy_level':
[4 2 3 5 1]
Unique values in column (Train) 'stress_level':
[2 4 1 5 3]
Unique values in column (Train) 'time_of_day':
<StringArray>
['afternoon', 'evening', 'night', 'morning', 'early_morning']
Length: 5, dtype: str
Unique values in column (Train) 'previous_day_mood':
<StringArray>
['mixed', 'calm', 'overwhelmed', 'focused', nan, 'neutral', 'restless']
Length: 7, dtype: str
Unique values in column (Train) 'face_emotion_hint':
<StringArray>
[   'calm_face',   'tired_face',   'happy_face',   'tense_face',
 'neutral_face',         'none',            nan]
Length: 7, dtype: str
Unique values in column (Train) 'reflection_quality'

In [ ]:
#missing values mostly in previous_day_mood and face_emotion_hint... and sleep_hours missing only in the train dataset. I probably should intoduce new features as "missing_netadata_feature". I will handle encoding in the modeling phase itslef, for better pipeline management(instead of modifying the original dataset)